title: CottonFoxUA
email: admin@cottonfoxua.com
mobile: +38 067 777 77 77
description: >
  Cotton Fox UA - just started.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
#twitter_username: jekyllrb
#github_username:  jekyll
lang: "ru"

# Build settings
source: src
sass:
  load_paths:
    - _sass
    - ../node_modules/bootstrap/scss
    - ../node_modules/font-awesome/scss
#  style: compressed # enable css compression

destination: public
markdown: kramdown

gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock
  - .gitignore

collections:
  dresses:
    output: true
    permalink: pretty