title: CottonFoxUA
email: admin@cottonfoxua.com
description: >
  Cotton Fox UA - just started.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
#twitter_username: jekyllrb
#github_username:  jekyll

# Build settings
source: src
destination: public
markdown: kramdown

theme: minima

gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock
  - .gitignore