title: CottonFoxUA
email: admin@cottonfoxua.com
mobile: +38 067 777 77 77
description: >
  Cotton Fox UA - just started.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
#twitter_username: jekyllrb
#github_username:  jekyll
lang: "ru"

# Build settings
source: src
sass:
  load_paths:
    - _sass
    - ../node_modules/bootstrap/scss
    - ../node_modules/font-awesome/scss
#  style: compressed # enable css compression

destination: public
markdown: kramdown

gems:
  - jekyll-feed
  - jekyll-responsive-image
exclude:
  - Gemfile
  - Gemfile.lock
  - .gitignore

collections:
  dresses:
    output: true

responsive_image:
  # [Required]
  # Path to the image template.
  template: _includes/responsive-image.html
  base_path: assets/images
  output_path_format: assets/resized/%{width}/%{basename}
  sizes:
    - width: 300
      quality: 65
    - width: 600
      quality: 75
    - width: 900
      quality: 90